# Last edited on 2010-03-17 17:51:39 by stolfi

PROG := virtual_gauge

JS_LIBS := \
  libraab.a \
  libimg.a \
  libgeo.a \
  libjs.a

OTHER_LIBS :=

MAYBE_LIBS :=

OTHER_LD_FLAGS := \
  -pg

include ../../GENERIC-PROGS.make
