# Last edited on 2009-02-21 16:29:58 by stolfi

PROG := \
  fit_ellipse_to_photo

JS_LIBS := \
  libpst.a \
  libminn.a \
  libminu.a \
  libimg.a \
  libgeo.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

