# Makefile for a package consisting of a single GAWK script
# Last edited on 2008-01-14 19:43:42 by stolfi

PROG := normal_to_photo

JS_LIBS := \
  libpst.a \
  libgeo.a \
  libimg.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
