# Makefile for a package consisting of a single GAWK script
# Last edited on 2008-01-14 19:43:34 by stolfi

PROG := make_sphere_normal_map

JS_LIBS := \
  libpst.a \
  libimg.a \
  libgeo.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
