# Last edited on 2025-01-08 16:58:09 by stolfi

PROG := make_test_slope_maps

JS_LIBS := \
  libpst.a \
  libgeo.a \
  libgausol.a \
  libimg.a \
  libjs.a \
  libjsextra.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libjpeg.so \
  /usr/lib/x86_64-linux-gnu/libpng.so \
  /usr/lib/x86_64-linux-gnu/libz.so

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

