# Last edited on 2018-06-30 04:55:50 by stolfilocal

PROG := make_test_slope_maps

JS_LIBS := \
  libpst.a \
  libgeo.a \
  libimg.a \
  libjs.a \
  libjsextra.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

