# Last edited on 2018-06-30 04:58:53 by stolfilocal

PROG := make_test_slope_maps
        
PROGDIR := ..

include ${STOLFIHOME}/programs/c/GENERIC-PROGS-TEST.make

# include DO-0032x0032.make
# include DO-0256x0256.make
include DO-0512x0512.make
