# Last edited on 2025-01-08 16:59:12 by stolfi

PROG := make_test_slope_maps
        
PROGDIR := ..

include ${STOLFIHOME}/programs/c/GENERIC-PROGS-TEST.make

all: run_tests.sh ${PROGDIR}/${PROG}
	run_tests.sh
        


